<script type="text/template" id="album-template">
    <div class="thumbnail-overlay">
        <span class="badge badge-inverse"><%= count %></span>
        <p><%= name %></p>
    </div>
</script>

<script type="text/template" id="photo-template">
  <img class="hidden" src="<%= picture %>" alt="" />
</script>
<div id="photobrowser-app" class="loading">
    <ul id="album-list" ></ul>
    <ul id="photo-list"></ul>
</div>