<script type="text/template" id="album-template">
    <img src="http://placehold.it/130x130" class="album-thumbnail">
    <p class="album-name"><%= name %></p>
</script>

<script type="text/template" id="photo-template">
    <img src="<%= picture %>">
    <p class="photo-id"><%= id %></p>
</script>
<div id="photobrowser-app" class="loading">

    <ul id="album-list"></ul>
    <ul id="photo-list"></ul>
</div>
