<?php

  // Define html tag's lang attribute
  $lang = 'en';
  if (Zend_Registry::isRegistered('Zend_Translate')) {
    $lang = Zend_Registry::get('Zend_Translate')->getLocale();
    $this->headTitle()->enableTranslation();
  }
?>

<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="<?php echo $lang ?>"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="<?php echo $lang ?>"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="<?php echo $lang ?>"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?php echo $lang ?>"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> -->

  <?php
    echo $this->headTitle('Site title', 'PREPEND')->setSeparator(' / ') . "\n";
    echo $this->headMeta() . "\n";
  ?>

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css">
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/style.css">
  <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/app.css">
  <?php echo $this->headStyle(); ?>

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <script src="<?php echo $this->baseUrl(); ?>/js/libs/modernizr-2.5.3.min.js"></script>
  <?php echo $this->headScript(); ?>
</head>
<body>
  <div id="fb-root"></div>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '273103992788017', // App ID
        channelUrl : 'http://photobrowser.local/index/channel', // Channel File
        status     : true, // check login status
        cookie     : true, // enable cookies to allow the server to access the session
        xfbml      : true  // parse XFBML
      });


      FB.login(function(response) {
        FB.api('/me/albums', function(response){
            window.App = new AppView();
        });
      }, {scope: 'user_photos'});

      // Additional initialization code here
    };

    // Load the SDK Asynchronously
    (function(d){
       var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement('script'); js.id = id; js.async = true;
       js.src = "//connect.facebook.net/en_US/all.js";
       ref.parentNode.insertBefore(js, ref);
     }(document));
  </script>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <header>

  </header>
  <div role="main">
    <?php echo $this->layout()->content; ?>
  </div>
  <footer>

  </footer>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/js/libs/jquery-1.7.1.min.js"><\/script>')</script>
  <script src="<?php echo $this->baseUrl(); ?>/js/underscore-1.3.3.min.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/js/backbone-0.9.2.min.js"></script>

  <!-- scripts concatenated and minified via build script -->
  <script src="<?php echo $this->baseUrl(); ?>/js/plugins.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/js/script.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/js/app/controllers.js"></script>
  <!-- end scripts -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Facebook Photo Browser</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

  <?php echo $this->inlineScript(); ?>

    </div> <!-- /container -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
</body>
</html>
