<?php

  // Define html tag's lang attribute
  $lang = 'en';
  if (Zend_Registry::isRegistered('Zend_Translate')) {
    $lang = Zend_Registry::get('Zend_Translate')->getLocale();
    $this->headTitle()->enableTranslation();
  }
?>

<!doctype html>

<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="<?php echo $lang ?>"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="<?php echo $lang ?>"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang="<?php echo $lang ?>"><![endif]-->

<!--[if gt IE 8]><!--> <html class=no-js lang="<?php echo $lang ?>"> <!--<![endif]-->
<head>
  <meta charset=utf-8>

  

  <?php
    echo $this->headTitle('Site title', 'PREPEND')->setSeparator(' / ') . "\n";
    echo $this->headMeta() . "\n";
  ?>

  
  <meta name=viewport content="width=device-width">

  

  <link rel=stylesheet href='<?php echo $this->baseUrl(); ?>/css/e68668b.css'>
  <?php echo $this->headStyle(); ?>

  

  
  <script src="<?php echo $this->baseUrl(); ?>/js/libs/modernizr-2.5.3.min.js"></script>
  <?php echo $this->headScript(); ?>
</head>
<body>
  
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <header>

  </header>
  <div role=main>
    <?php echo $this->layout()->content; ?>
  </div>
  <footer>

  </footer>


  

  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/js/libs/jquery-1.7.1.min.js"><\/script>')</script>

  <script src='<?php echo $this->baseUrl(); ?>/js/af93a9b.js'></script>
  <?php echo $this->inlineScript(); ?>

  
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
</body>
</html>